language: scala
scala:
  - 2.11.8
  - 2.12.0
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
matrix:
  exclude: # NB: Scala 2.12 requires JDK 8
  - scala: 2.12.0
    jdk: oraclejdk7
  - scala: 2.12.0
    jdk: openjdk7

sudo: false
script:
  - sbt checkHeaders
  - sbt coverage doc test tut
  - sbt coverageReport
after_success:
  - pip install --user codecov && codecov
